#+title: Clove

Successor to [[https://github.com/russmatney/clover][russmatney/clover]], but dropping Electron in favor of Tauri.

Builds a binary that can be passed a window title and URL, to host a locally
running web app outside of your usual browser tabs.

I use this in [[https://github.com/russmatney/clawe][russmatney/clawe]] to run a clojurescript topbar and dashboard on linux and OSX.

More detail on my blog:

- [[https://danger.russmatney.com/daily/2022-10-18.html][2022-10-18 daily note]]
- [[https://danger.russmatney.com/note/tauri_as_a_simple_native_web_view.html][Tauri as a simple native webview]]

* updating
things like
#+begin_src
rustup update
yarn global upgrade @tauri-apps/cli@latest
tauri migrate
cargo update # in src-tauri/
tauri dev

./src-tauri/target/debug/clove create-window -t mytitle --url http://localhost:3333 --label mylabel
#+end_src

~tauri dev~ with commands fails lately b/c `dev` adds extra command line args
that tauri-plugin-cli doesn't support :eyeroll:

~tauri dev~ on mac currently fails completely, dep resolution fail for hyper-tls?

migration from tauri 1 guide: https://v2.tauri.app/start/migrate/from-tauri-1/


* Dev
Build:

#+begin_src sh
cargo tauri dev
#+end_src

Test:

#+begin_src sh
./src-tauri/target/debug/clove create-window -t mytitle --url http://localhost:3333 --label mylabel
#+end_src
* 'Prod'
#+begin_src sh
NO_STRIP=true cargo tauri build
#+end_src

~NO_STRIP=true~ from https://github.com/tauri-apps/tauri/issues/8929

Test the prod build:

#+begin_src sh
./src-tauri/target/release/clove create-window -t mytitle --url http://localhost:3333 --label mylabel
#+end_src
* install
Build prod and install it in ~/.cargo/bin:

#+begin_src sh
cargo install --path src-tauri/.
#+end_src
* Usage

#+begin_src sh
clove create-window \
    --title some-window-title \
    --url http://localhost:3333 \
    --label some-unique-label
#+end_src

Eg at default clerk port:

#+begin_src sh
clove create-window \
    --title clerk-notebook \
    --url http://localhost:8888 \
    --label clerk-notebook
#+end_src

With more args:

#+begin_src sh
clove create-window \
    --transparent \
    --decorations \
    --focused \
    --title clerk-notebook \
    --url http://localhost:8888 \
    --label clerk-notebook
#+end_src
* misc
** nvidia error
There is a crash when running tauri against the latest nvidia renderers:

#+begin_src sh
src/nv_gbm.c:99: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)

Failed to create GBM buffer of size 2279x999: Invalid argument
#+end_src

For now using an env var makes things work again:

#+begin_src sh
WEBKIT_DISABLE_DMABUF_RENDERER=1 clove create-window ....
#+end_src

Some related threads:

- https://github.com/tauri-apps/tauri/issues/7910
- https://www.reddit.com/r/rust/comments/16tzu8w/tauri_issue/
- https://www.reddit.com/r/tauri/comments/16tzsi8/tauri_desktop_app_not_rendering_but_web_does/
** linuxdeploy fail
add ~NO_STRIP=true~ (from: https://github.com/tauri-apps/tauri/issues/8929 )
